version: '3'
services:
  firefly_iii_client_generator:
    build:
      context: .
      args:
        - OPENAPI_TAG=v6.6.0
    volumes:
      - ./target:/build/target
      - .:/build/src
      - ./.generator:/generator
    environment:
      API_VERSION: 2.0.12
      API_SUBVERSION: "-v1"
      PACKAGE_BUILD: 0