# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import firefly_iii_client
from firefly_iii_client.paths.v1_webhooks_id_trigger_transaction_transaction_id import post  # noqa: E501
from firefly_iii_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1WebhooksIdTriggerTransactionTransactionId(ApiTestMixin, unittest.TestCase):
    """
    V1WebhooksIdTriggerTransactionTransactionId unit test stubs
        Trigger webhook for a given transaction.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
